### ISSUE TITLE
Kplex can't bind to device

### ISSUE THREAD

**Issue by munnik** [stripydog/kplex#31]
I've got the following kplex.conf:
```
[udp]
direction=in
port=10110
device=enp1s0

[pty]
direction=out
mode=master
filename=/home/lambert/.opencpn/nmea
baud=115200
owner=lambert
group=lambert
perm=600

[udp]
direction=out
address=192.168.1.255
port=60001

[udp]
name=GN0001
direction=out
device=enp6s0
address=239.192.0.1
port=60001
srctag=yes
timestamp=ms
ofilter=+GP***:-all

[udp]
name=GN0002
direction=out
device=enp7s0
address=239.192.0.1
port=60001
srctag=yes
timestamp=ms
ofilter=+GP***:-all
```

and when I try to run kplex I get this ouput
```bash
sudo kplex -d9
kplex DEBUG: kplex starting, config file /etc/kplex.conf
kplex DEBUG: _udp-id1: BINDTODEVICE failed on device enp1s0: No such file or directory
kplex DEBUG: udp interface _udp-id1 listening on 0.0.0.0, port 10110
kplex DEBUG: _pty-id2: created pty link /home/lambert/.opencpn/nmea to /dev/pts/3
kplex DEBUG: _udp-id3: output address 192.168.1.255, port 60001
kplex DEBUG: GN0001: BINDTODEVICE failed on device enp6s0
kplex DEBUG: GN0001: output address 239.192.0.1, port 60001
kplex DEBUG: GN0002: BINDTODEVICE failed on device enp7s0
kplex DEBUG: GN0002: output address 239.192.0.1, port 60001
```

I've got the following network configuration
```
ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp2s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:90:e8:78:be:cf brd ff:ff:ff:ff:ff:ff
3: enp7s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:90:e8:78:be:d1 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.1/24 brd 10.0.2.255 scope global enp7s0
       valid_lft forever preferred_lft forever
    inet6 fe80::290:e8ff:fe78:bed1/64 scope link
       valid_lft forever preferred_lft forever
4: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:90:e8:78:be:ce brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.112/24 brd 192.168.1.255 scope global enp1s0
       valid_lft forever preferred_lft forever
    inet6 fe80::290:e8ff:fe78:bece/64 scope link
       valid_lft forever preferred_lft forever
5: enp6s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:90:e8:78:be:d0 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.1/24 brd 10.0.1.255 scope global enp6s0
       valid_lft forever preferred_lft forever
    inet6 fe80::290:e8ff:fe78:bed0/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by stripydog** [comment]
Warning message aside, does it "work"?

SO_BINDTODEVICE only works for the root user so the warning are "expected behaviour".  It's also not supported on all platforms so we try at and don't make a fuss if it doesn't work, although you see it in debug output.  There's a comment about it in the source but there should probably be an update to the documentation.

The question is why I'm bothering to do it in the case of output only interfaces....

If you can confirm that things are actually working here and you're just concerned about the warnings, then the "fix" for me is to investigate whether there's any benefit to trying it on an output interface (I don't think there is) and updating the documentation

**Comment by munnik** [comment]
My issue is resolved now because I run as root, when I was debugging I was running it as a non root user. I think the `device` option is mandatory when `type` is multicast and you use ip address 239.192.0.3. If that is the case then I think it should not be a warning because kplex cannot determine on what interface to send the data.

**Comment by stripydog** [comment]
Hey...sorry to have overlooked coming back to you on this.  Specifying a device is not mandatory for multicast interfaces: if you don't specify a device the default multicast interface (as determined by the routing table) will be used.  I believe (correct me if I'm wrong) that your point here is that failure to bind to device will not result in the required behaviour if you specify a non-default interface as a non-root user on a system which requires root fo SO_BINDTODEVICE so this should be an error rather than a warning.  Yours is a case which supports that.  I'm sure I had a good reason to make this a warning rather than an error, although I can't quite remember what it was now :-)

It's been a while since I played with this but I've just been experimenting on ubuntu 18.0.4 (4.15 kernel) and seems you don't need to be root to use SO_BINDTODEVICE any more: it all seems to be working OK including creating 2 separate kplex interfaces each binding to a separate network interface with the same multicast group and port: netstat -g is showing me the group joined on both interfaces and I can see packets multicasted out of each interface with different source addresses.

Do you still have an issue with this?  And if so have you tried a 4.x or 5.x kernel?

**Comment by stripydog** [comment]
I'll leave this open for another 5 days.  If there's something else you think needs doing, let me know before then
