### ISSUE TITLE
Make install error 1

### ISSUE THREAD

**Issue by jwillmer** [stripydog/kplex#37]
I get the following error when trying to install on Debian 10. How can I fix it?

![image](https://user-images.githubusercontent.com/1503577/88533698-fe1e4800-d006-11ea-9b07-09ea3f9b66d5.png)

**Comment by jwillmer** [comment]
Adding `mkdir /usr/share/man/man1` fixed the error. Can someone tell me what this test does and if my solution is ok and not just tricking the test to succeed?

**Comment by stripydog** [comment]
The test is checking whether /usr/share/man/man1 which kplex assumes is its
man page installation location exists before installing the (rudimentary)
kplex man page there.  The logic is slightly different in the develop
branch which better copes with installations outside the main tree.  If you
didn't have a /usr/share/man/man1 and are not installing outside your
system's main tree then either you don't have man pages installed or debian
10 is keeping them somewhere else.  Perhaps you have the man pages under a
locale-specific subdirectory of /usr/share/man?

If kplex.1.gz is now installed, do you get a man page if you type man kplex?

Let me know because it seems like one way or another I'll need to update
the Makefile (thanks for raising this)

**Comment by jwillmer** [comment]
Ah, o.k., no I get it. No I don't have man page installed. I'm currently working on [containerizing your application](https://github.com/jwillmer/kplex). Expect a pull request soon!
