### ISSUE TITLE
Apprently manpage has errors.... 

### ISSUE THREAD

**Issue by FredericGuilbault** [stripydog/kplex#44]
IDK anything about manpages but the debian package linter complain about this: 

```
kplex: manpage-has-errors-from-man usr/share/man/man1/kplex.1.gz  line 16: 'R' is a string (producing the registered sign), not a macro.
```
```
kplex: manpage-section-mismatch usr/share/man/man1/kplex.1.gz:1 1 != 8
```

**Comment by stripydog** [comment]
For the first part..".R" (switch to Roman) appears to be obsolete.  It's referenced in some older docs on the man macro set but as you've found doesn't work with modern groff.  I have hopefully resolved this (groff -Tasicc -man doesn't throw errors anyway).

The second part was a mismatch between an incorrect man section heading (8) and the (correct) install location (1).

Thanks for spotting both of those and let me know if they are fixed in the update I just pushed to the develop branch

**Comment by FredericGuilbault** [comment]
Thx, Ill check that hopefully by the end of next week and if the linter is good with it. ill close this issue.

**Comment by FredericGuilbault** [comment]
Yep, Commit f6a0d01f5238ef4eb639201ce9fbe770c712876d fix it. Good job.
