### ISSUE TITLE
Can not use UDP broadcast.

### ISSUE THREAD

**Issue by kmpm** [stripydog/kplex#6]
I cloned the source from github and compiled with succes.
I got everything I tried to work except UDP broadcast.
When I tried to launch kplex (and debug) it looked like the UDP interfaced closed immediately
```
sudo ./kplex -d 9
kplex DEBUG: Using config file /home/user/.kplex.conf
kplex DEBUG: Cleaning up data for exiting interface myudp
```
The other interface (tcp) did not close until I pressed Ctrl+C.
If I changed to the deprecated [broadcast] instead it all worked fine.

This was done on Ubuntu 14.04.3 on a Dell computer with only wifi0 connected.
The NMEA output came from the Chrome App "NMEA Simulator"

non working config
```
[tcp]
name=mytcp
mode=client
direction=in
address=127.0.0.1

[udp]
name=myudp
port=2000
direction=out
type=broadcast
device=wlan0
```

working config
```
[tcp]
name=mytcp
mode=client
direction=in
address=127.0.0.1

[broadcast]
name=mybroadcast
port=2000
device=wlan0
```

**Comment by stripydog** [comment]
Hi Peter,

I will look at this tomorrow but I think it may be something which I'd
noticed earlier, meant to fix but forgot about.  I'm guessing that you have
ipv6 enabled on wlan0, even if you only have a link-local address and a
default gai.conf.

If that *is* the problem what happens is that kplex finds wlan0 but the
first "interface" it finds is the ipv6 one which of course doesn't support
broadcast.

I will re-visit this and see how I can improve things but the workarounds
are:
1. use "broadcast" as you have done
2. explicitly state the broadcast address you want to use (e.g.
"address=192.168.1.255" in the udp interface declaration)
3. Change your /etc/gai.conf file to return ipv4 addresses from lookups
before ipv6.

Let me know if that sounds plausible or if you think something else is
going on.

Keith

**Comment by stripydog** [comment]
Nope, scrub that.  I think I did fix that problem and created another.  Still investigating but it seems on Linux to be picking up on AF_PACKET interfaces (which I should have filtered out).  Still working on it but don't bother with the above workarounds....

**Comment by stripydog** [comment]
Here's the scoop.  I had a missing bit of logic to restrict interface associated with a device to AF_INET and AF_INET6 and on Linux the first interface returned was the packet interface.  The workaround is to explicitly specify the broadcast address in the kplex interface declaration: That should work.  I'm currently looking at the logic to ensure that any fix I put in copes equally well with IPv4 broadcast interfaces and IPv4 and IPv6 point-to-point interfaces which should all be specifiable by device rather than address.  I'll update this when I've got a fix I can live with

**Comment by stripydog** [comment]
I've put in a fix and fixed another bug I found in the course of this.  Can you pull the latest code from the develop branch and check that it works for you?  Thanks

**Comment by kmpm** [comment]
Will check later today
Den 18 nov. 2015 4:44 em skrev "stripydog" <notifications@github.com>:

**Comment by stripydog** [comment]
Any luck?

**Comment by kmpm** [comment]
Sorry, something came up... Will do it this weekend

**Comment by stripydog** [comment]
Any update?  I'd like to close this and possibly release a minor update

**Comment by kmpm** [comment]
Tested today without any success.
Nothing gets broadcasted at all. But since I have logging to file as well and that works I know there is NMEA data flowing.

**Comment by stripydog** [comment]
Sorry for the delay: been avoiding computers over christmas.  Found the (or at least a) problem.  Again manifestation is down to the order in which the system returns an interface's addresses.  Need to figure out whether a quick kludge or something a bit more structural is the way to go here.

**Comment by kmpm** [comment]
Take your time and do it properly. Maintain code that was written as a
quick fix usually comes back haunting you.
Den 4 jan. 2016 11:31 fm skrev "stripydog" <notifications@github.com>:

**Comment by stripydog** [comment]
Turns out I was wrong, it was simpler than I thought and also realise why I didn't catch it in testing.  The previous fix had added in a path where port wouldn't be set if port was explicitly stated but no address was given. I'd been testing with no address but leaving port at default .  Try the develop branch on github now.

**Comment by stripydog** [comment]
If you get a chance to test the develop branch to see if this has been
resolved I will start preparing a new minor release.

**Comment by stripydog** [comment]
Any chance you could test out the develop branch?  I've fixed a couple of nasty bugs in the last few days and would like to close this one off if it is indeed fixed.  Thanks.

**Comment by stripydog** [comment]
Peter,

I have a release candidate on the web site to download (1.3.2rc2):
http://www.stripydog.com/kplex/download.html
If you could check that this issue is resolved I'd be really grateful.  If I don't hear back from you by the 11th April I'll assume this *is* fixed (I hope it is) and close the issue (you can always reopen it)

**Comment by stripydog** [comment]
OK, nothing heard.  Hopefully it should be fixed: please re-open if not
