### ISSUE TITLE
Output files not truncated

### ISSUE THREAD

**Issue by patricktokeeffe** [stripydog/kplex#7]
I'm observing output files are not truncated when they should be. Even if `append=no` is explicitly specified, the output file is appended to.

```
pi@airmar200wx:~ $ kplex -V
1.3.1
pi@airmar200wx:~ $ uname -a
Linux airmar200wx 4.1.13+ #826 PREEMPT Fri Nov 13 20:13:22 GMT 2015 armv6l GNU/Linux
```
kplex config:
```
[serial]
filename=/dev/ttyAMA0
direction=both
baud=4800

[tcp]
mode=server
port=10110
direction=out

[file]
filename=/tmp/file
direction=out
#append=no
```

Results:

```
pi@airmar200wx:~ $ ls /tmp -l
total 20
-rw-r--r-- 1 kplex kplex 19051 Jan 12 21:17 file
pi@airmar200wx:~ $ ls /tmp -l
total 24
-rw-r--r-- 1 kplex kplex 21414 Jan 12 21:17 file
pi@airmar200wx:~ $ ls /tmp -l
total 24
-rw-r--r-- 1 kplex kplex 21602 Jan 12 21:17 file
pi@airmar200wx:~ $ ls /tmp -l
total 24
-rw-r--r-- 1 kplex kplex 21887 Jan 12 21:17 file
pi@airmar200wx:~ $ ls /tmp -l
total 24
-rw-r--r-- 1 kplex kplex 22408 Jan 12 21:17 file
```

**Comment by stripydog** [comment]
Sorry to be ignorant here but can you explain the ls?  Is the lastmod time
the same because you typed it 5 times within a minute?  In which case
surely you didn't restart kplex between each invocation of ls?

In case there's some confusion...the truncate/append functionality applies
to what kplex does with an existing file *on startup* rather than with each
sentence.  Without "append=yes" an *existing* log file will be truncated
*on startup*.  Once kplex is up and running, sentences are always appended
(i.e. each sentence logged doesn't overwrite the previous one).

I've just double checked that that functionality is working correctly on an
x86_64 system (ubuntu): I don't have an arm system with me at the moment.

Can you let me know if this is a misunderstanding of the functionality or
do you still think it's a bug?

**Comment by patricktokeeffe** [comment]
OK, thanks for clarifying. I didn't find mention of when the truncation would occur in the documentation and (mis)interpreted things. For what I'm trying to accomplish, a psuedoterminal is making more sense anyway.
